[platformio]
src_dir = src
build_dir = .pio/build

[env:rover]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  ESP32Async/AsyncTCP
  ESP32Async/ESPAsyncWebServer
